name: Release
on:
  push:
    tags:
      - "v\+d"

jobs:
  release:
    name: Testing and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install packages
        run: npm ci

      # Билд проекта
      - name: Build
        run: npm run build

      # Тестирование
      - name: Unit tests
        run: npm run test-ci

      - name: Lint
        run: npm run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: e2e tests
        run: npm run e2e-ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Формирование changelog
      - name: Get current and previous tag
        run: |
          echo "PREV_TAG=git describe --abbrev=0 --tags `git rev-list --tags --skip=1  --max-count=1`" >> $GITHUB_ENV
          echo "CUR_TAG=git describe --abbrev=0 --tags" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0 #TODO: bump this after release
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ env.PREV_TAG }}
          base-ref: ${{ env.CUR_TAG }}
          fetch: false

      # Создание артефактов для GH Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: ./build

  deploy:
    needs: release
    permissions:
      pages: write # to deploy to Pages
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
