name: Pull request testing
on:
  pull_request:

jobs:
  test:
    name: Test commits into PR
    runs-on: ubuntu-latest
    steps:
      - name: Tests and build
        uses: ./github/workflows/testing.yml
