name: Pull request testing
on:
  pull_request:

jobs:
  test:
    name: Test commits into PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tests and build
        uses: ./github/workflows/testing.yml
