name: Pull request testing
on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install packages
        run: npm ci

      # Проверка с помощью commitlint
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      # Билд проекта
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build
          path: build/
          retention-days: 30

      # Тестирование
      - name: Unit tests
        run: npm run test-ci

      - name: Lint
        run: npm run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: e2e tests
        run: npm run e2e-ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
