name: Pull request testing
on:
  pull_request:

jobs:
  test:
    name: Test commits into PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install packages
        run: npm ci

      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Validate PR commits with commitlint
        run: git log -1 --pretty=format:"%s" | npx commitlint
        
      # Билд проекта
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build
          path: build/
          retention-days: 30

      # Тестирование
      - name: Unit tests
        run: npm run test-ci

      - name: Lint
        run: npm run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: e2e tests
        run: npm run e2e-ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
