name: CI
on:
  pull_request:

jobs:
  verify:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: gh pr 1
      - name: gh pr status
        run: gh pr checkout 12
