name: Release
on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  release:
    name: Testing and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install packages
        run: npm ci

      # Билд проекта
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build
          path: build/
          retention-days: 30

      # Тестирование
      - name: Unit tests
        run: npm run test-ci

      - name: Lint
        run: npm run lint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: e2e tests
        run: npm run e2e-ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy on Github pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
