name: Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release:
    name: Testing and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tests and build
        uses: ./.github/workflows/testing.yml

      - name: Deploy on Github pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
