name: Test
on:
  push:

jobs:
  changelog:
    name: Testing and release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
      issues: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      # Формирование changelog
      # Формирование информации о пользователе
      - name: Get current commit info
        run: |
          git log --name-status HEAD^..HEAD >> changelog.md
          echo "____________________________________" >> changelog.md
      # Формирование коммитов
      - name: Get current and previous tag
        run: |
          echo "PREV_TAG=git describe --abbrev=0 --tags `git rev-list --tags --skip=1  --max-count=1`" >> $GITHUB_ENV
          echo "CUR_TAG=git describe --abbrev=0 --tags" >> $GITHUB_ENV
      - name: Get tags hashes
        run: |
          echo "PREV_HASH=git show-ref -s ${{ env.PREV_TAG }}" >> $GITHUB_ENV
          echo "CUR_HASH=git show-ref -s ${{ env.CUR_TAG }}" >> $GITHUB_ENV
      #- name: Git oneline commits
       # run: git log ${{ env.PREV_HASH }}..${{ env.CUR_HASH }} --oneline >> changelog.md
        # Формирование коммитов
      - name: Create issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue create --title "RELEASE ${{ env.CUR_TAG }}" --body-file ./changelog.md
