name: Test
on:
  push:

jobs:
  changelog:
    name: Testing and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      # Формирование changelog
      - name: Get current and previous tag
        run: |
          git describe --abbrev=0 --tags `git rev-list --tags --skip=1  --max-count=1`
          git describe --abbrev=0 --tags
